# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
rvm: ruby-head
cache: cocoapods
podfile: Example/Podfile
before_install:
- rvm get stable --auto-dotfiles
- rvm install 2.3.0
- rvm use 2.3.0
- gem install cocoapods
- pod update --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/CZPicker.xcworkspace -scheme CZPicker-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
